// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

type Message struct {
	ID        string  `json:"id"`
	Content   *string `json:"content,omitempty"`
	MediaURL  *string `json:"mediaURL,omitempty"`
	MediaType *string `json:"mediaType,omitempty"`
	Timestamp *string `json:"timestamp,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
