[build]
  command = "NODE_OPTIONS=--max_old_space_size=4096 npm run build"
  publish = "build"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"
    X-Robots-Tag = "noindex"

# 정적 파일 처리를 위한 설정
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = false