[build]
  command = "NODE_OPTIONS=--max_old_space_size=4096 npm run build"
  publish = "build"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    X-Robots-Tag = "index, follow"
    Cache-Control = "public, max-age=0"