// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

type ChatRoom struct {
	ID       string      `json:"id"`
	Members  []*UserInfo `json:"members"`
	Messages []string    `json:"messages"`
}

type Login struct {
	UserID   string `json:"user_id"`
	Password string `json:"password"`
}

type Message struct {
	ID          string `json:"id"`
	ChatRoomID  string `json:"chatRoomID"`
	Timestamp   string `json:"timestamp"`
	MessageType string `json:"messageType"`
	Content     string `json:"content"`
	From        string `json:"from"`
	To          string `json:"to"`
}

type MessageInput struct {
	ChatRoomID  string `json:"chatRoomID"`
	Timestamp   string `json:"timestamp"`
	MessageType string `json:"messageType"`
	Content     string `json:"content"`
	From        string `json:"from"`
	To          string `json:"to"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type UserInfo struct {
	ID           string  `json:"id"`
	UserID       string  `json:"user_id"`
	Nickname     string  `json:"nickname"`
	Password     string  `json:"password"`
	ProfileImage *string `json:"profile_image,omitempty"`
}

type UserInput struct {
	UserID       string  `json:"user_id"`
	Nickname     string  `json:"nickname"`
	Password     string  `json:"password"`
	ProfileImage *string `json:"profile_image,omitempty"`
}
